workdir: /hpi/fs00/home/fabio.malchermiranda/scratch/hiclass/benchmarks/consumer_complaints

threads: 12

data: 'https://files.consumerfinance.gov/ccdb/complaints.csv.zip'

# Random state used for splitting the data in training and test
random_state: 42

# Number of folds for cross-validation
n_splits: 5

# Memory allocated for tune and train rules
mem_gb: 450

# Uncomment the next line to use a subset of the data
#nrows: 2000

classifiers:
  - logistic_regression
  - random_forest
  - lightgbm

models:
  - flat
  - local_classifier_per_node
  - local_classifier_per_parent_node
  - local_classifier_per_level
